#%RAML 1.0 Library
usage: To define data types alias names

types:
  customerReq: !include ../data-types/requests/select-req.raml
  customerRes: !include ../data-types/responses/select-res.raml
  insertReq: !include ../data-types/requests/insert-req.raml
  insertRes: !include ../data-types/responses/insert-res.raml
  insertMulReq: !include ../data-types/requests/insert-mule-req.raml
  insertMulRes: !include ../data-types/responses/insert-mule-res.raml