#%RAML 1.0 DataType
type: array
description: This is used to define RAML for employee api 
items:
  properties:
    ckey:
      type: string
      description: This will provide api response http status.
      displayName: name
      example: "15077"    
