#%RAML 1.0 DataType
type: array
description: this is customer api input raml spec
items:
  properties:
    name:
      type: string
      description: this will provide the name 
      displayName: name
      example: "triveni"
    position:
      type: string
      description: customer position in org.
      displayName: position
      example: "Lead"